### ISSUE TITLE
Warning thrown at initiation that box has undefined dtype

### ISSUE THREAD

**Issue by awade** [CaltechExperimentalGravity/gym#2]
I'm getting the message when I initiate env with
`>env = gym.make('VacCan-v0')`

> WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.

I think when the box space is initiated it needs an explicit data type for those variables.  Its probably fine but given that we are running integration ode solvers, where precision might matter,  its probably best if we are explicit.

**Comment by shruti-jm** [comment]
Added dtype = numpy.float64 to to observation space, this warning should no longer appear

**Comment by awade** [comment]
Repulled and looks like fixed.  Thanks.
